#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: fendou2017
#      maximum-pool-size: 50



#h2  数据库
server:
  port: 8089

# 为了启动数据库H2界面
spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url:  jdbc:h2:~/test
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: 123456


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

