
servers:
 # ipAddress: 192.168.0.1     # 驼峰模式
 # ipaddress:  192.168.0.2
 # ip-address:  192.168.0.3   # 烤肉串模式 0-0-0-0-0
 # ip_address:  192.168.0.4
 # IPADDRESS:  192.168.0.5
 # IP_ADDRESS:  192.168.0.6   #常量模式
#IP-ADDRESS:  192.168.0.7
  IP_ADD_RE-SS:  192.168.0.8
  port: 2345
  timeout: -1

datasource:
  driverClassName: com.mysql.jdbc.Driver789
